baseURL = 'https://aschepis.github.io/mutual-aid-list/'
languageCode = 'en-us'
title = 'Mutual Aid Needs'
theme = 'mutual-aid'

[params]
  description = 'Direct links to mutual aid needs in Massachusetts and New England. Connecting people who need help with those who can provide it.'
